# Generated by Django 3.0.7 on 2023-08-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('1', 'Vestuário Tático'), ('2', 'Armamento e Munição'), ('3', 'Equipamento de Comunicação'), ('4', 'Equipamento de Sobrevivência'), ('5', 'Equipamento de Missões Especiais'), ('6', 'Veículos Militares'), ('7', 'Equipamentos de Engenharia'), ('8', 'Equipamento de Inteligência e Vigilância'), ('9', 'Equipamento Médico Militar'), ('10', 'Equipamento de Logística'), ('11', 'Equipamento de Treinamento'), ('12', 'Equipamento de Sapa'), ('13', 'Outros')], default='13', max_length=2),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='qtd',
            field=models.IntegerField(default=0),
        ),
    ]
